version: '2'
services:
  book-service:
    image:
      ghcr.io/yash0412/bootcamp-project-bookshop-service:latest
    container_name: bookshop-service
    ports:
      - "8080:8080"

  book-ui:
    image:
      ghcr.io/yash0412/bootcamp-project-bookshop-ui:latest
    container_name: bookshop-ui
    ports:
      - "80:80"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: