server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookshop
    username: postgres
    password: pass123
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true