server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    username: postgres
    password: pass123
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB

  flyway:
    enabled: true