DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    id VARCHAR(50) PRIMARY KEY,
    title  VARCHAR(200) NOT NULL,
    author VARCHAR(50) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    quantity NUMERIC NOT NULL,
    imageUrl VARCHAR(500)
);