# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Run Unit and Integration Tests and Deploy to Dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Run-Unit-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2 # v2.6.0
      with:
        arguments: test

  Build-And-Publish:
    name: Build Jar And Docker Image And Publish Image to GHCR
    runs-on: ubuntu-latest
    needs: Run-Unit-Test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2 # v2.6.0
      with:
        arguments: build
    - name: Create docker image
      run: docker build -t bookshop-service:${{github.sha}} .
    - name: Publish Docker Image to GHCR
      uses: macbre/push-to-ghcr@master
      with:
        image_name: bookshop-service:${{github.sha}}
        github_token: ${{ secrets.ACTION_TOKEN }}
    

  Integration-Test:
    runs-on: ubuntu-latest
    needs: Build-And-Publish
    steps:
      - uses: actions/checkout@v3
      - run: echo "Starting Integration Tests"
      - run: echo "Integration Tests In Progress..."
      - run: echo "Integration Tests Completed"
  

  Dev-Deployment:
    runs-on: ubuntu-latest
    needs: Integration-Test
    steps:
      - uses: actions/checkout@v3
      - run: echo "Starting Deployment to Dev"
      - run: echo "Deployment to Dev In Progress..."
      - run: echo "Deployed to Dev"
