# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit SHA1 to build'
        required: true
        type: string

permissions:
  contents: read

jobs:
  Pull-Image:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
      - name: Pull Image from GHCR
        run: docker pull ghcr.io/${{ github.repository }}.toLowerCase()/${{ inputs.refToBuild }}.toLowerCase()

  Production-Deployment:
    runs-on: ubuntu-latest
    needs: Pull-Image
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refToBuild }}
      - run: echo "Starting Deployment to Production with commit ID ${{ inputs.refToBuild }}"
      - run: echo "Fetching Dev image for Deployment"
      - run: echo "Deployment to Production In Progress..."
      - run: echo "Deployed to Production"
